### ISSUE TITLE
Require relative paths doesn't unwind

### ISSUE THREAD

**Issue by d3x0r** [letorbi/smoothie#12]
I've been considering a simple case to demonstrate, but I'll just post what I noticed for now.

I have a project something like

Voxelarium/Voxelarium.js - requires ./src/voxels.js
Voxelarium/src/voxels.js - required dynamically (./voxes/voxel_###.js) until it fails to find the next in line. (the 6 that are known to work do load correctly)
then Voxelarium.js requires ./src/sector.js

at this point the request that goes to the server is 'http://localhost/src/src/sector.js' (it keeps 'src' in there from when voxels.js loaded a requirement from a relative path... 

---Voxelarim.js---

require( "./src/voxels.js" )
require( "./src/sector.js" )

-- Voxels.js ---
require( "./voxels/voxel_1.js" );

---

In voxels.js I previously was doing

```
        xhrObj.open('GET', `./src/voxels/voxel_${n}.js`, false);
        xhrObj.send(null);
        eval(xhrObj.responseText);

        //require( `./voxels/voxel_${n}.js` )
```

which I realized I could just replace with require now that I'm using your module... but then loading started failing.

**Comment by letorbi** [comment]
Hi, thx for reporting. I hope I'll find some time to investigate the issue during the weekend.

**Comment by letorbi** [comment]
Sorry for answering so late. I've created a new branch, which contains a lot of improvements, which might fix this issue. Can you check whether your problem still exits when you use the ['tarp'](https://github.com/letorbi/smoothie/tree/tarp) branch of this repository?
