### ISSUE TITLE
The operation is insecure. on firefox if I try to use HTTPS but HTTP works

### ISSUE THREAD

**Issue by CheyenneForbes** [letorbi/smoothie#14]

**Comment by letorbi** [comment]
Hej Cheyenne,

it seems quite unlikely to me that this problem is caused by smoothie as it does not enforce the use of HTTP anywhere. Can you give me an example where this error occurs?

Bye
Torben

**Comment by CheyenneForbes** [comment]
Hi Torben,

after seeing your comment I got an idea to check the library I was trying to import and it wasn't smoothie causing the error, I thought it was because the console output was "https://192.168.1.3/client/js/mqtt.js: The operation is insecure. require.js:36:0"
